DROP SEQUENCE careID;
CREATE TABLE LoginForm (
username VARCHAR(20) NOT NULL, 
email VARCHAR(50) NOT NULL PRIMARY KEY,
password VARCHAR(20) NOT NULL
);
DROP TABLE LOGINFORM;
position VARCHAR(20) NOT NULL,
phoneNumber VARCHAR(20) NOT NULL

drop table loginform;