ALTER SESSION SET CONTAINER = XEPDB1;
CREATE USER test IDENTIFIED BY password;
ALTER USER test DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
ALTER USER test TEMPORARY TABLESPACE TEMP;
GRANT CONNECT TO test;
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE TO 
test;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE, UNLIMITED TABLESPACE TO test;