CREATE SEQUENCE personID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE registrationID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE assignmentID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE registrationID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE repairNum
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE order_num
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE TABLE Person(
    ID NUMBER PRIMARY KEY NOT NULL,
    FirstName VARCHAR(20) NOT NULL,
    LastName VARCHAR(20) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    Password VARCHAR(20) NOT NULL,
    Position VARCHAR(10) NOT NULL
);

CREATE TABLE staff(
    staffID NUMBER  NOT NULL PRIMARY KEY,
    FOREIGN KEY(staffID) REFERENCES Person(ID)
);

CREATE TABLE Mechanic(
    mechID NUMBER NOT NULL PRIMARY KEY,
    FOREIGN KEY(mechID) REFERENCES Person(ID)
);

CREATE TABLE Client(
    clientID NUMBER NOT NULL PRIMARY KEY,
    FOREIGN KEY(clientID) REFERENCES Person(ID)
);

CREATE TABLE Vehicle(
    Plate_num VARCHAR(8) NOT NULL PRIMARY KEY,
    Type VARCHAR(10) NOT NULL,
    clientID NUMBER NOT NULL,
    FOREIGN KEY(clientID) REFERENCES Client(clientID)
);

CREATE TABLE JobDetails(
    Type VARCHAR(40) PRIMARY KEY NOT NULL,
    Description VARCHAR(120) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Phone VARCHAR(20) NOT NULL
);

CREATE TABLE ActiveJobs(
    Type VARCHAR(40) NOT NULL,
    personID NUMBER NOT NULL,
    mechID NUMBER NOT NULL,
    FOREIGN KEY(personID) REFERENCES Person(ID),
    FOREIGN KEY(mechID) REFERENCES Mechanic(mechID),
    FOREIGN KEY(Type) REFERENCES JobDetails(Type)

);

CREATE TABLE Assignment(
    ID NUMBER NOT NULL PRIMARY KEY,
    staffID NUMBER NOT NULL,
    mechID NUMBER NOT NULL,
    jobType VARCHAR(40),
    FOREIGN KEY(jobType) REFERENCES JobDetails(Type)
);

CREATE TABLE Registration(
    ID NUMBER NOT NULL PRIMARY KEY,
    staffID NUMBER,
    clientID NUMBER,
    Plate_num VARCHAR(8),
    FOREIGN KEY(staffID) REFERENCES Person(ID), 
    FOREIGN KEY(clientID) REFERENCES Person(ID),
    FOREIGN KEY(Plate_num) REFERENCES Vehicle(Plate_num)

);

CREATE TABLE Repair(
    repairNum NUMBER NOT NULL PRIMARY KEY,
    clientID NUMBER,
    FOREIGN KEY(clientID) REFERENCES Client(clientID)

);

CREATE TABLE vehicleComponents(
    Type VARCHAR(15) NOT NULL PRIMARY KEY,
    Cost NUMBER(8) NOT NULL
);

CREATE TABLE Orders(
    Order_num NUMBER PRIMARY KEY NOT NULL,
    Type VARCHAR(20) NOT NULL,
    clientID NUMBER NOT NULL,
    FOREIGN KEY(clientID) REFERENCES Client(clientID),
    FOREIGN KEY(Type) REFERENCES Accessories(Type)

);


CREATE TABLE Accessories(
    Type VARCHAR(20) PRIMARY KEY NOT NULL,
    Cost NUMBER(8) NOT NULL
);